-- Se procede a realizar la creacion de las tablas Departamentos y Empleados

CREATE TABLE departamentos (
  id_departamento NUMBER PRIMARY KEY,
  nombre_departamento VARCHAR2(100) NOT NULL
);

CREATE TABLE empleados (
  id_empleado NUMBER PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  apellido VARCHAR2(100) NOT NULL,
  correo VARCHAR2(150) NOT NULL,
  salario NUMBER(10,2) NOT NULL,
  id_departamento NUMBER NOT NULL,
  CONSTRAINT fk_empleado_departamento
    FOREIGN KEY (id_departamento)
    REFERENCES departamentos(id_departamento)
);

CREATE TABLE empleados_xml (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  documento XMLTYPE,
  observacion VARCHAR2(200)
);

--------------------------------------------------------------------------------
-- Se procede a crear los departamentos 


INSERT INTO departamentos VALUES (10, 'Administración');
INSERT INTO departamentos VALUES (20, 'Recursos Humanos');
INSERT INTO departamentos VALUES (30, 'Tecnología');
INSERT INTO departamentos VALUES (40, 'Contabilidad');
INSERT INTO departamentos VALUES (50, 'Ventas');

--------------------------------------------------------------------------------
-- Se procede a realizar el registro de los empleados


INSERT INTO empleados VALUES (100, 'Carlos', 'Ramírez', 'carlos.ramirez@gmail.com', 3500000, 10);
INSERT INTO empleados VALUES (101, 'Laura', 'Gómez', 'laura.gomez@hotmail.com', 4200000, 20);
INSERT INTO empleados VALUES (102, 'Andrés', 'Martínez', 'andres.martinez@gmail.com', 5100000, 30);
INSERT INTO empleados VALUES (103, 'Camila', 'Torres', 'camila.torres@outlook.com', 3900000, 40);
INSERT INTO empleados VALUES (104, 'Juan', 'Pérez', 'juan.perez@gmail.com', 2800000, 50);
INSERT INTO empleados VALUES (105, 'María', 'Fernández', 'maria.fernandez@gmail.com', 3650000, 10);
INSERT INTO empleados VALUES (106, 'Santiago', 'Herrera', 'santiago.herrera@hotmail.com', 4450000, 20);
INSERT INTO empleados VALUES (107, 'Valentina', 'Morales', 'valentina.morales@outlook.com', 5300000, 30);
INSERT INTO empleados VALUES (108, 'Diego', 'Castro', 'diego.castro@gmail.com', 4100000, 40);
INSERT INTO empleados VALUES (109, 'Daniela', 'Rojas', 'daniela.rojas@yahoo.com', 2950000, 50);
INSERT INTO empleados VALUES (110, 'Felipe', 'Vargas', 'felipe.vargas@gmail.com', 3800000, 10);
INSERT INTO empleados VALUES (111, 'Natalia', 'Suárez', 'natalia.suarez@hotmail.com', 4600000, 20);
INSERT INTO empleados VALUES (112, 'Sebastián', 'Ortega', 'sebastian.ortega@gmail.com', 5500000, 30);
INSERT INTO empleados VALUES (113, 'Paula', 'Mendoza', 'paula.mendoza@outlook.com', 4300000, 40);
INSERT INTO empleados VALUES (114, 'Miguel', 'Navarro', 'miguel.navarro@gmail.com', 3100000, 50);

COMMIT;

--------------------------------------------------------------------------------

SELECT e.id_empleado,
       e.nombre,
       e.apellido,
       e.correo,
       e.salario,
       d.nombre_departamento AS departamento
FROM empleados e
JOIN departamentos d
ON e.id_departamento = d.id_departamento
ORDER BY e.id_empleado;

--------------------------------------------------------------------------------
-- CONSULTAS XPATH Y XQUERY EN ORACLE
--------------------------------------------------------------------------------

-- Todos los empleados del XML

SELECT x.id,
       x.nombre,
       x.apellido,
       x.correo,
       x.salario,
       x.departamento
FROM empleados_xml t,
     XMLTABLE(
       '/empleados/empleado'
       PASSING t.documento
       COLUMNS
         id VARCHAR2(20) PATH '@id',
         nombre VARCHAR2(100) PATH 'nombre',
         apellido VARCHAR2(100) PATH 'apellido',
         correo VARCHAR2(150) PATH 'correo',
         salario VARCHAR2(50) PATH 'salario',
         departamento VARCHAR2(100) PATH 'departamento'
     ) x
WHERE t.observacion = 'XML válido'
ORDER BY TO_NUMBER(x.id);

-- Solo nombres de empleados

SELECT x.nombre
FROM empleados_xml t,
     XMLTABLE(
       '/empleados/empleado'
       PASSING t.documento
       COLUMNS
         nombre VARCHAR2(100) PATH 'nombre'
     ) x
WHERE t.observacion = 'XML válido'
ORDER BY x.nombre;

-- Nombres, apellidos y salario

SELECT x.nombre,
       x.apellido,
       x.salario
FROM empleados_xml t,
     XMLTABLE(
       '/empleados/empleado'
       PASSING t.documento
       COLUMNS
         nombre VARCHAR2(100) PATH 'nombre',
         apellido VARCHAR2(100) PATH 'apellido',
         salario VARCHAR2(50) PATH 'salario'
     ) x
WHERE t.observacion = 'XML válido'
ORDER BY x.nombre;

-- Empleados con salario mayor a 4000000

SELECT x.nombre,
       x.apellido,
       x.salario,
       x.departamento
FROM empleados_xml t,
     XMLTABLE(
       '/empleados/empleado[salario > 4000000]'
       PASSING t.documento
       COLUMNS
         nombre VARCHAR2(100) PATH 'nombre',
         apellido VARCHAR2(100) PATH 'apellido',
         salario VARCHAR2(50) PATH 'salario',
         departamento VARCHAR2(100) PATH 'departamento'
     ) x
WHERE t.observacion = 'XML válido'
ORDER BY TO_NUMBER(x.salario) DESC;

-- Empleados del departamento Administración

SELECT x.id,
       x.nombre,
       x.apellido,
       x.correo,
       x.salario,
       x.departamento
FROM empleados_xml t,
     XMLTABLE(
       '/empleados/empleado[departamento = "Administración"]'
       PASSING t.documento
       COLUMNS
         id VARCHAR2(20) PATH '@id',
         nombre VARCHAR2(100) PATH 'nombre',
         apellido VARCHAR2(100) PATH 'apellido',
         correo VARCHAR2(150) PATH 'correo',
         salario VARCHAR2(50) PATH 'salario',
         departamento VARCHAR2(100) PATH 'departamento'
     ) x
WHERE t.observacion = 'XML válido'
ORDER BY TO_NUMBER(x.id);

----------
 SELECT x.nombre
FROM empleados_xml t,
     XMLTABLE(
       '/empleados/empleado'
       PASSING t.documento
       COLUMNS
         nombre VARCHAR2(100) PATH 'nombre'
     ) x
WHERE t.observacion = 'XML válido';